language: python

python: "3.4"

env:
  global:
    - secure: "Y7lb8qI7Nf1pviTfHXYmqP2XvXhCeXfWzcUiI1b02pJgO/cQCdjZrI4QmHPB6i4zNakwHWyO2lH88EiaXPb1Vu3ADebEEix78Fp70O0cINknMRtbJT5d0LcBCND9bbzQy6SFEg94DcX6f6gUmMc2chhRSBirZWrS82qkmjKVhHSejdav8xH3W3fZiujpa5AWm6u45O8gWMyPk4OgXOU49xwaiStwHiaouOyYUO/xiOjcT9Ivr3xzAJDo/UFdn/Qq2DvSeeKIAyfmdpmtoD+DJHX6yhqw9FhyQvt57MOSvEhQQLcH06fnJsevBefdBaxBXMZb2sE96dz3LDB8zsi/UjNY/1ZqfVJKbgWZ76EwbOlVZNy0FnA1T7jqVXFHh2Ljxm2EaEQVHkMSadKIRovvRduQp0x5dpisUnXSzrAoKvDbGJYFql+u82iH9rrHtubN0XhN5tqKNB9XGEBpCqya5aVS76O/hwBRQNSVluSfE+lBFQYTvqL/HZKTuDB2mkM7qY+tRWLCN0CgY5T4Y/I4nI6Q+LOs186hJvh2fDWx0KN+ItNMVHIVlDu1sK4N0pVSN8N9JJvFEX8caqXVk0pbD1mGAXfkyUjWJadCiRlAGFQ8yVFRBcZArPpn3BaasuTB9IuiV2fCwN1VyEYs8DzqGuvTgAQGjZsRpBBwv20wadk="

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libxml2-dev
      - libxslt1-dev
      - texlive
      - haskell-platform
      - emacs-nox

install:
  - pip install Nikola[extras]
  - nikola plugin -i orgmode
  - cabal update
  - cabal install pandoc pandoc-citeproc
  - mkdir -p $HOME/.emacs.d/src
  - wget http://orgmode.org/org-8.3.1.tar.gz
  - tar -C ~/.emacs.d/src/ -xvzf org-8.3.1.tar.gz

before_script:
  - export PATH=$PATH:$HOME/.cabal/bin/
  - sed -i "1i (let* ((org-lisp-dir \"~/.emacs.d/src/org-8.3.1/lisp\")) (when (file-directory-p org-lisp-dir) (add-to-list \'load-path org-lisp-dir) (require \'org)))" plugins/orgmode/init.el

script: nikola build

after_success:
  - chmod 755 ./.push_gh_pages.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./.push_gh_pages.sh
